import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

// Verify the checked-in app AND the projects regenerated by CocoaPods.
// This is intentionally read-only: do not hide invalid settings in a build flag.
const appURL = new URL('../App.xcodeproj/project.pbxproj', import.meta.url);
const podsURL = new URL('../Pods/Pods.xcodeproj/project.pbxproj', import.meta.url);
const pattern = /IPHONEOS_DEPLOYMENT_TARGET\s*=\s*"?([0-9]+(?:\.[0-9]+)*)"?\s*;/g;
try {
  for (const [label, url] of [['App', appURL], ['Pods', podsURL]]) {
    const contents = await readFile(url, 'utf8');
    const targets = [...contents.matchAll(pattern)].map(match => match[1]);
    assert(targets.length > 0, `${label}: no explicit numeric iOS targets found.`);
    assert(targets.every(version => Number(version.split('.')[0]) >= 15),
      `${label}: deployment targets below iOS 15 remain: ${targets.join(', ')}`);
    console.log(`PASS ${label}: ${targets.length} deployment settings, all iOS 15 or later.`);
    if (label === 'App') {
      assert(contents.includes('PRODUCT_BUNDLE_IDENTIFIER = com.pawssible.chorely;'),
        'Unexpected app identity; refusing to archive the wrong application.');
    }
  }
} catch (error) {
  console.error(`error: ${error.message}`);
  process.exitCode = 1;
}
